
ARG DOCKER_VERSION=22.09
ARG BASE_IMAGE=nvcr.io/nvidia/pytorch:${DOCKER_VERSION}-py3
FROM ${BASE_IMAGE}

RUN apt-get update && \
    apt-get install -y --no-install-recommends bc git-lfs && \
    apt-get install -y libaio-dev && \
    apt-get install -y sysstat && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN python -m pip install --upgrade pip
RUN pip install pydantic --upgrade

ADD  req_new.txt . 
RUN pip install -r req_new.txt
